
name: PR Summary

on:
  pull_request_target:

permissions:
  pull-requests: write

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: pr-branch

      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: base-branch

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Lean
        uses: leanprover/lean-action@v1.3.0
        with:
          lint: false

      - name: Build base branch
        run: |
          cd base-branch
          lake build > ../base-build.log 2>&1 || true
          cd ..

      - name: Build PR branch
        run: |
          cd pr-branch
          lake build > ../pr-build.log 2>&1 || true
          cd ..

      - name: Install dependencies
        run: pip install -r ./base-branch/scripts/requirements.txt

      - name: Get PR diff
        run: |
          diff -uprN base-branch pr-branch > pr.diff || true

      - name: Generate summary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          BASE_BUILD_LOG: ${{ steps.base_build.outputs.log }}
          PR_BUILD_LOG: ${{ steps.pr_build.outputs.log }}
        run: |
          python ./base-branch/scripts/pr-summary.py
