
name: PR Summary

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: pr-branch

      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: base-branch

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r ./pr-branch/scripts/requirements.txt

      - name: Get PR diff
        id: diff
        run: |
          diff -uprN base-branch pr-branch > pr.diff || true
          echo 'diff<<EOF' >> $GITHUB_OUTPUT
          cat pr.diff >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Generate summary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_DIFF: ${{ steps.diff.outputs.diff }}
        run: |
          python ./pr-branch/scripts/pr-summary.py
