name: PR Summary

on:
  pull_request_target:

permissions:
  pull-requests: write

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: pr-branch

      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: base-branch

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install elan
        run: |
          curl -sSfL https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | sh -s -- -y --no-modify-path
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Build base branch
        run: lake build > ../base-build.log 2>&1
        working-directory: ./base-branch
        continue-on-error: true

      - name: Build PR branch
        run: lake build > ../pr-build.log 2>&1
        working-directory: ./pr-branch
        continue-on-error: true

      - name: Install Python dependencies
        run: pip install -r ./base-branch/scripts/requirements.txt

      - name: Get PR diff
        run: |
          diff -uprN base-branch pr-branch > pr.diff || true

      - name: Generate summary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          python ./base-branch/scripts/pr-summary.py